### ISSUE TITLE
Opacity lost when editing card

### ISSUE THREAD

**Issue by jamiekoi** [lovac42/DancingBaloney#4]
I have my background set to 50% opacity, but when I am revewing a card, and I press E for edit, the opacity is temporarily 100% (see pics)

[Pic1: main decks screen; opacity 50%)
![image](https://user-images.githubusercontent.com/61689283/77432191-a7dd9600-6dd5-11ea-93df-967b8de87b76.png)

[Pic2: edit screen background; opacity 100%]
![image](https://user-images.githubusercontent.com/61689283/77432331-d2c7ea00-6dd5-11ea-9abf-d129a1cdb106.png)

Not really an issue, but would be great if the edit background maintained same opacity. Thanks for your godly work!

**Comment by lovac42** [comment]
The current version doesn't show background during reviews yet. Are you using themes? There is a css file called resetRequired.css in the other themes. Use it as an example and set opacity to 0.5.

**Comment by jamiekoi** [comment]
Hi, 
No, I'm not using themes. [Here's a screen recording to give an idea](https://youtu.be/SCK-xteQKmc)

And here's how to replicate my issue:
1. Set a custom background (.gif or .png)
2. Set opacity to 50% for example
3. While you are on the main screen (as in pic1), pull up the adding dialogue and add a new card to any deck.
4. As soon as you click "add", the screen in the background will show "waiting for editing to finish" and the background will have an opacity of 100%
5. if you close the add dialogue, things go back to your perferred 50% opacity

So this happens when you add new cards (i.e., the screen is showing "waiting for editing to finish" or when you press edit during review.

**Comment by lovac42** [comment]
Thanks I'll look into it.
