### ISSUE TITLE
Suggestion: Changing fonts colours

### ISSUE THREAD

**Issue by idkei** [lovac42/DancingBaloney#9]
Hi,

great & nice addon to anki!

I was wondering if it's possible to be able to change colour of fonts on the main window? as using a dark background pic or gif would make the fonts hard to see. I don't fancy using dark windows as it makes everything dark when I'm reviewing the cards. Hope it's easy to implement.

thanks for the addon though! works wonderfully and I can have a soothing picture on the main window.

**Comment by lovac42** [comment]
Looks like someone has already answered your question in the main anki forum. You can use CSS to do that. I don't really have control over those part of anki and would need to add in extra code to allow those features which is guaranteed to cause conflict.
